export const professionalsData = [
  {
    id: 1,
    name: "Dr. Juan Pérez",
    specialty: "Psicología Infantil",
    location: "Quito",
    phone: "+593 99 123 4567",
    email: "juan.perez@aura.com",
    website: "www.drjuanperez.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 12,
  },
  {
    id: 2,
    name: "Dra. María González",
    specialty: "Terapia Ocupacional",
    location: "Guayaquil",
    phone: "+593 99 234 5678",
    email: "maria.gonzalez@aura.com",
    website: "www.mariagonzalez.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 8,
  },
  {
    id: 3,
    name: "Lic. Carlos Mendoza",
    specialty: "Educación Especial",
    location: "Manabí",
    phone: "+593 99 345 6789",
    email: "carlos.mendoza@aura.com",
    website: "www.carlosmendoza.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 15,
  },
  {
    id: 4,
    name: "Dra. Ana Rodríguez",
    specialty: "Odontología",
    location: "Quito",
    phone: "+593 99 456 7890",
    email: "ana.rodriguez@aura.com",
    website: "www.anarodriguez.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 10,
  },
  {
    id: 5,
    name: "Lic. Pedro Sánchez",
    specialty: "Fonoaudiología",
    location: "Guayaquil",
    phone: "+593 99 567 8901",
    email: "pedro.sanchez@aura.com",
    website: "www.pedrosanchez.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 7,
  },
  {
    id: 6,
    name: "Dr. Luis Martínez",
    specialty: "Neurología",
    location: "Quito",
    phone: "+593 99 678 9012",
    email: "luis.martinez@aura.com",
    website: "www.luismartinez.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 20,
  },
  {
    id: 7,
    name: "Dra. Carmen Torres",
    specialty: "Psiquiatría",
    location: "Manabí",
    phone: "+593 99 789 0123",
    email: "carmen.torres@aura.com",
    website: "www.carmentorres.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 14,
  },
  {
    id: 8,
    name: "Lic. Roberto Flores",
    specialty: "Psicología Infantil",
    location: "Guayaquil",
    phone: "+593 99 890 1234",
    email: "roberto.flores@aura.com",
    website: "www.robertoflores.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 9,
  },
  {
    id: 9,
    name: "Dra. Isabel Ramírez",
    specialty: "Terapia Ocupacional",
    location: "Quito",
    phone: "+593 99 901 2345",
    email: "isabel.ramirez@aura.com",
    website: "www.isabelramirez.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 11,
  },
  {
    id: 10,
    name: "Dr. Fernando Castro",
    specialty: "Educación Especial",
    location: "Manabí",
    phone: "+593 99 012 3456",
    email: "fernando.castro@aura.com",
    website: "www.fernandocastro.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 13,
  },
  {
    id: 11,
    name: "Dra. Patricia Morales",
    specialty: "Odontología",
    location: "Guayaquil",
    phone: "+593 99 123 4568",
    email: "patricia.morales@aura.com",
    website: "www.patriciamorales.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 6,
  },
  {
    id: 12,
    name: "Lic. Diego Vargas",
    specialty: "Fonoaudiología",
    location: "Quito",
    phone: "+593 99 234 5679",
    email: "diego.vargas@aura.com",
    website: "www.diegovargas.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 8,
  },
  {
    id: 13,
    name: "Dr. Andrés Herrera",
    specialty: "Neurología",
    location: "Manabí",
    phone: "+593 99 345 6780",
    email: "andres.herrera@aura.com",
    website: "www.andresherrera.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 18,
  },
  {
    id: 14,
    name: "Dra. Sofía Jiménez",
    specialty: "Psiquiatría",
    location: "Guayaquil",
    phone: "+593 99 456 7891",
    email: "sofia.jimenez@aura.com",
    website: "www.sofiajimenez.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 16,
  },
  {
    id: 15,
    name: "Lic. Miguel Ortiz",
    specialty: "Psicología Infantil",
    location: "Quito",
    phone: "+593 99 567 8902",
    email: "miguel.ortiz@aura.com",
    website: "www.miguelortiz.com",
    image: "/placeholder.svg?height=400&width=400",
    experience: 5,
  },
]
